# for local test
version: "3.9"
services:
  batch-db:
    image: mysql:8.0.33
    container_name: batch-db
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3307:3306"